/* soapDoorControlBindingProxy.cpp
   Generated by gSOAP 2.8.134 for samples/onvif/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapDoorControlBindingProxy.h"

DoorControlBindingProxy::DoorControlBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	DoorControlBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

DoorControlBindingProxy::DoorControlBindingProxy(const DoorControlBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

DoorControlBindingProxy::DoorControlBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	DoorControlBindingProxy_init(_soap->imode, _soap->omode);
}

DoorControlBindingProxy::DoorControlBindingProxy(struct soap *_soap, const char *soap_endpoint_url)
{	this->soap = _soap;
	this->soap_own = false;
	DoorControlBindingProxy_init(_soap->imode, _soap->omode);
	soap_endpoint = soap_endpoint_url;
}

DoorControlBindingProxy::DoorControlBindingProxy(const char *soap_endpoint_url)
{	this->soap = soap_new();
	this->soap_own = true;
	DoorControlBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

DoorControlBindingProxy::DoorControlBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	DoorControlBindingProxy_init(iomode, iomode);
}

DoorControlBindingProxy::DoorControlBindingProxy(const char *soap_endpoint_url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	DoorControlBindingProxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

DoorControlBindingProxy::DoorControlBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	DoorControlBindingProxy_init(imode, omode);
}

DoorControlBindingProxy::~DoorControlBindingProxy()
{	if (this->soap_own)
	{	DoorControlBindingProxy::destroy();
		soap_free(this->soap);
	}
}

void DoorControlBindingProxy::DoorControlBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL },
        { "ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL },
        { "saml1", "urn:oasis:names:tc:SAML:1.0:assertion", NULL, NULL },
        { "saml2", "urn:oasis:names:tc:SAML:2.0:assertion", NULL, NULL },
        { "wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL },
        { "xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL },
        { "wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL },
        { "wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL },
        { "wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", "http://www.w3.org/2005/08/addressing", NULL },
        { "wsdd", "http://schemas.xmlsoap.org/ws/2005/04/discovery", NULL, NULL },
        { "chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL },
        { "wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL },
        { "ns2", "http://www.onvif.org/ver20/analytics/humanbody", NULL, NULL },
        { "ns1", "http://www.onvif.org/ver20/analytics/humanface", NULL, NULL },
        { "ns5", "http://www.onvif.org/ver10/pacs", NULL, NULL },
        { "xmime", "http://tempuri.org/xmime.xsd", NULL, NULL },
        { "xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL },
        { "tt", "http://www.onvif.org/ver10/schema", NULL, NULL },
        { "wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL },
        { "wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL },
        { "wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL },
        { "ns3", "http://www.onvif.org/ver10/actionengine/wsdl", NULL, NULL },
        { "ns4", "http://www.onvif.org/ver10/accesscontrol/wsdl", NULL, NULL },
        { "ns6", "http://www.onvif.org/ver10/doorcontrol/wsdl", NULL, NULL },
        { "tad", "http://www.onvif.org/ver10/analyticsdevice/wsdl", NULL, NULL },
        { "tan", "http://www.onvif.org/ver20/analytics/wsdl", NULL, NULL },
        { "tdn", "http://www.onvif.org/ver10/network/wsdl", NULL, NULL },
        { "tds", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL },
        { "tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL },
        { "wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL },
        { "timg", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL },
        { "tls", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL },
        { "tmd", "http://www.onvif.org/ver10/deviceIO/wsdl", NULL, NULL },
        { "tptz", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL },
        { "trc", "http://www.onvif.org/ver10/recording/wsdl", NULL, NULL },
        { "trp", "http://www.onvif.org/ver10/replay/wsdl", NULL, NULL },
        { "trt", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL },
        { "trv", "http://www.onvif.org/ver10/receiver/wsdl", NULL, NULL },
        { "tse", "http://www.onvif.org/ver10/search/wsdl", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this->soap, namespaces);
}

DoorControlBindingProxy *DoorControlBindingProxy::copy()
{	DoorControlBindingProxy *dup = SOAP_NEW_UNMANAGED(DoorControlBindingProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

DoorControlBindingProxy& DoorControlBindingProxy::operator=(const DoorControlBindingProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void DoorControlBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void DoorControlBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	DoorControlBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void DoorControlBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void DoorControlBindingProxy::soap_header(struct _wsse__Security *wsse__Security, char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct wsdd__AppSequenceType *wsdd__AppSequence, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance)
{
	::soap_header(this->soap);
	this->soap->header->wsse__Security = wsse__Security;
	this->soap->header->wsa__MessageID = wsa__MessageID;
	this->soap->header->wsa__RelatesTo = wsa__RelatesTo;
	this->soap->header->wsa__From = wsa__From;
	this->soap->header->wsa__ReplyTo = wsa__ReplyTo;
	this->soap->header->wsa__FaultTo = wsa__FaultTo;
	this->soap->header->wsa__To = wsa__To;
	this->soap->header->wsa__Action = wsa__Action;
	this->soap->header->wsdd__AppSequence = wsdd__AppSequence;
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
}

::SOAP_ENV__Header *DoorControlBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *DoorControlBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *DoorControlBindingProxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this->soap);
}

const char *DoorControlBindingProxy::soap_fault_string()
{	return ::soap_fault_string(this->soap);
}

const char *DoorControlBindingProxy::soap_fault_detail()
{	return ::soap_fault_detail(this->soap);
}

int DoorControlBindingProxy::soap_close_socket()
{	return ::soap_closesock(this->soap);
}

int DoorControlBindingProxy::soap_force_close_socket()
{	return ::soap_force_closesock(this->soap);
}

void DoorControlBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void DoorControlBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *DoorControlBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int DoorControlBindingProxy::send_GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns6__GetServiceCapabilities *ns6__GetServiceCapabilities)
{
	struct __ns6__GetServiceCapabilities soap_tmp___ns6__GetServiceCapabilities;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetServiceCapabilities";
	soap_tmp___ns6__GetServiceCapabilities.ns6__GetServiceCapabilities = ns6__GetServiceCapabilities;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities, "-ns6:GetServiceCapabilities", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetServiceCapabilities(soap, &soap_tmp___ns6__GetServiceCapabilities, "-ns6:GetServiceCapabilities", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_GetServiceCapabilities(_ns6__GetServiceCapabilitiesResponse &ns6__GetServiceCapabilitiesResponse)
{
	ns6__GetServiceCapabilitiesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetServiceCapabilitiesResponse.soap_get(soap, "ns6:GetServiceCapabilitiesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_GetDoorInfoList(const char *soap_endpoint_url, const char *soap_action, _ns6__GetDoorInfoList *ns6__GetDoorInfoList)
{
	struct __ns6__GetDoorInfoList soap_tmp___ns6__GetDoorInfoList;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfoList";
	soap_tmp___ns6__GetDoorInfoList.ns6__GetDoorInfoList = ns6__GetDoorInfoList;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetDoorInfoList(soap, &soap_tmp___ns6__GetDoorInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetDoorInfoList(soap, &soap_tmp___ns6__GetDoorInfoList, "-ns6:GetDoorInfoList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetDoorInfoList(soap, &soap_tmp___ns6__GetDoorInfoList, "-ns6:GetDoorInfoList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_GetDoorInfoList(_ns6__GetDoorInfoListResponse &ns6__GetDoorInfoListResponse)
{
	ns6__GetDoorInfoListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetDoorInfoListResponse.soap_get(soap, "ns6:GetDoorInfoListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_GetDoorInfo(const char *soap_endpoint_url, const char *soap_action, _ns6__GetDoorInfo *ns6__GetDoorInfo)
{
	struct __ns6__GetDoorInfo soap_tmp___ns6__GetDoorInfo;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorInfo";
	soap_tmp___ns6__GetDoorInfo.ns6__GetDoorInfo = ns6__GetDoorInfo;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetDoorInfo(soap, &soap_tmp___ns6__GetDoorInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetDoorInfo(soap, &soap_tmp___ns6__GetDoorInfo, "-ns6:GetDoorInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetDoorInfo(soap, &soap_tmp___ns6__GetDoorInfo, "-ns6:GetDoorInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_GetDoorInfo(_ns6__GetDoorInfoResponse &ns6__GetDoorInfoResponse)
{
	ns6__GetDoorInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetDoorInfoResponse.soap_get(soap, "ns6:GetDoorInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_GetDoorList(const char *soap_endpoint_url, const char *soap_action, _ns6__GetDoorList *ns6__GetDoorList)
{
	struct __ns6__GetDoorList soap_tmp___ns6__GetDoorList;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorList";
	soap_tmp___ns6__GetDoorList.ns6__GetDoorList = ns6__GetDoorList;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetDoorList(soap, &soap_tmp___ns6__GetDoorList);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetDoorList(soap, &soap_tmp___ns6__GetDoorList, "-ns6:GetDoorList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetDoorList(soap, &soap_tmp___ns6__GetDoorList, "-ns6:GetDoorList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_GetDoorList(_ns6__GetDoorListResponse &ns6__GetDoorListResponse)
{
	ns6__GetDoorListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetDoorListResponse.soap_get(soap, "ns6:GetDoorListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_GetDoors(const char *soap_endpoint_url, const char *soap_action, _ns6__GetDoors *ns6__GetDoors)
{
	struct __ns6__GetDoors soap_tmp___ns6__GetDoors;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoors";
	soap_tmp___ns6__GetDoors.ns6__GetDoors = ns6__GetDoors;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetDoors(soap, &soap_tmp___ns6__GetDoors);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetDoors(soap, &soap_tmp___ns6__GetDoors, "-ns6:GetDoors", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetDoors(soap, &soap_tmp___ns6__GetDoors, "-ns6:GetDoors", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_GetDoors(_ns6__GetDoorsResponse &ns6__GetDoorsResponse)
{
	ns6__GetDoorsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetDoorsResponse.soap_get(soap, "ns6:GetDoorsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_CreateDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__CreateDoor *ns6__CreateDoor)
{
	struct __ns6__CreateDoor soap_tmp___ns6__CreateDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/CreateDoor";
	soap_tmp___ns6__CreateDoor.ns6__CreateDoor = ns6__CreateDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__CreateDoor(soap, &soap_tmp___ns6__CreateDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__CreateDoor(soap, &soap_tmp___ns6__CreateDoor, "-ns6:CreateDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__CreateDoor(soap, &soap_tmp___ns6__CreateDoor, "-ns6:CreateDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_CreateDoor(_ns6__CreateDoorResponse &ns6__CreateDoorResponse)
{
	ns6__CreateDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__CreateDoorResponse.soap_get(soap, "ns6:CreateDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_SetDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__SetDoor *ns6__SetDoor)
{
	struct __ns6__SetDoor soap_tmp___ns6__SetDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/SetDoor";
	soap_tmp___ns6__SetDoor.ns6__SetDoor = ns6__SetDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__SetDoor(soap, &soap_tmp___ns6__SetDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__SetDoor(soap, &soap_tmp___ns6__SetDoor, "-ns6:SetDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__SetDoor(soap, &soap_tmp___ns6__SetDoor, "-ns6:SetDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_SetDoor(_ns6__SetDoorResponse &ns6__SetDoorResponse)
{
	ns6__SetDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__SetDoorResponse.soap_get(soap, "ns6:SetDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_ModifyDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__ModifyDoor *ns6__ModifyDoor)
{
	struct __ns6__ModifyDoor soap_tmp___ns6__ModifyDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/ModifyDoor";
	soap_tmp___ns6__ModifyDoor.ns6__ModifyDoor = ns6__ModifyDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__ModifyDoor(soap, &soap_tmp___ns6__ModifyDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__ModifyDoor(soap, &soap_tmp___ns6__ModifyDoor, "-ns6:ModifyDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__ModifyDoor(soap, &soap_tmp___ns6__ModifyDoor, "-ns6:ModifyDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_ModifyDoor(_ns6__ModifyDoorResponse &ns6__ModifyDoorResponse)
{
	ns6__ModifyDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__ModifyDoorResponse.soap_get(soap, "ns6:ModifyDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_DeleteDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__DeleteDoor *ns6__DeleteDoor)
{
	struct __ns6__DeleteDoor soap_tmp___ns6__DeleteDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/DeleteDoor";
	soap_tmp___ns6__DeleteDoor.ns6__DeleteDoor = ns6__DeleteDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__DeleteDoor(soap, &soap_tmp___ns6__DeleteDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__DeleteDoor(soap, &soap_tmp___ns6__DeleteDoor, "-ns6:DeleteDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__DeleteDoor(soap, &soap_tmp___ns6__DeleteDoor, "-ns6:DeleteDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_DeleteDoor(_ns6__DeleteDoorResponse &ns6__DeleteDoorResponse)
{
	ns6__DeleteDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__DeleteDoorResponse.soap_get(soap, "ns6:DeleteDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_GetDoorState(const char *soap_endpoint_url, const char *soap_action, _ns6__GetDoorState *ns6__GetDoorState)
{
	struct __ns6__GetDoorState soap_tmp___ns6__GetDoorState;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/GetDoorState";
	soap_tmp___ns6__GetDoorState.ns6__GetDoorState = ns6__GetDoorState;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__GetDoorState(soap, &soap_tmp___ns6__GetDoorState);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__GetDoorState(soap, &soap_tmp___ns6__GetDoorState, "-ns6:GetDoorState", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__GetDoorState(soap, &soap_tmp___ns6__GetDoorState, "-ns6:GetDoorState", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_GetDoorState(_ns6__GetDoorStateResponse &ns6__GetDoorStateResponse)
{
	ns6__GetDoorStateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__GetDoorStateResponse.soap_get(soap, "ns6:GetDoorStateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_AccessDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__AccessDoor *ns6__AccessDoor)
{
	struct __ns6__AccessDoor soap_tmp___ns6__AccessDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/AccessDoor";
	soap_tmp___ns6__AccessDoor.ns6__AccessDoor = ns6__AccessDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__AccessDoor(soap, &soap_tmp___ns6__AccessDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__AccessDoor(soap, &soap_tmp___ns6__AccessDoor, "-ns6:AccessDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__AccessDoor(soap, &soap_tmp___ns6__AccessDoor, "-ns6:AccessDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_AccessDoor(_ns6__AccessDoorResponse &ns6__AccessDoorResponse)
{
	ns6__AccessDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__AccessDoorResponse.soap_get(soap, "ns6:AccessDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_LockDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__LockDoor *ns6__LockDoor)
{
	struct __ns6__LockDoor soap_tmp___ns6__LockDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockDoor";
	soap_tmp___ns6__LockDoor.ns6__LockDoor = ns6__LockDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__LockDoor(soap, &soap_tmp___ns6__LockDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__LockDoor(soap, &soap_tmp___ns6__LockDoor, "-ns6:LockDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__LockDoor(soap, &soap_tmp___ns6__LockDoor, "-ns6:LockDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_LockDoor(_ns6__LockDoorResponse &ns6__LockDoorResponse)
{
	ns6__LockDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__LockDoorResponse.soap_get(soap, "ns6:LockDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_UnlockDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__UnlockDoor *ns6__UnlockDoor)
{
	struct __ns6__UnlockDoor soap_tmp___ns6__UnlockDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/UnlockDoor";
	soap_tmp___ns6__UnlockDoor.ns6__UnlockDoor = ns6__UnlockDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__UnlockDoor(soap, &soap_tmp___ns6__UnlockDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__UnlockDoor(soap, &soap_tmp___ns6__UnlockDoor, "-ns6:UnlockDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__UnlockDoor(soap, &soap_tmp___ns6__UnlockDoor, "-ns6:UnlockDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_UnlockDoor(_ns6__UnlockDoorResponse &ns6__UnlockDoorResponse)
{
	ns6__UnlockDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__UnlockDoorResponse.soap_get(soap, "ns6:UnlockDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_BlockDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__BlockDoor *ns6__BlockDoor)
{
	struct __ns6__BlockDoor soap_tmp___ns6__BlockDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/BlockDoor";
	soap_tmp___ns6__BlockDoor.ns6__BlockDoor = ns6__BlockDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__BlockDoor(soap, &soap_tmp___ns6__BlockDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__BlockDoor(soap, &soap_tmp___ns6__BlockDoor, "-ns6:BlockDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__BlockDoor(soap, &soap_tmp___ns6__BlockDoor, "-ns6:BlockDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_BlockDoor(_ns6__BlockDoorResponse &ns6__BlockDoorResponse)
{
	ns6__BlockDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__BlockDoorResponse.soap_get(soap, "ns6:BlockDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_LockDownDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__LockDownDoor *ns6__LockDownDoor)
{
	struct __ns6__LockDownDoor soap_tmp___ns6__LockDownDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockDownDoor";
	soap_tmp___ns6__LockDownDoor.ns6__LockDownDoor = ns6__LockDownDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__LockDownDoor(soap, &soap_tmp___ns6__LockDownDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__LockDownDoor(soap, &soap_tmp___ns6__LockDownDoor, "-ns6:LockDownDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__LockDownDoor(soap, &soap_tmp___ns6__LockDownDoor, "-ns6:LockDownDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_LockDownDoor(_ns6__LockDownDoorResponse &ns6__LockDownDoorResponse)
{
	ns6__LockDownDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__LockDownDoorResponse.soap_get(soap, "ns6:LockDownDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_LockDownReleaseDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__LockDownReleaseDoor *ns6__LockDownReleaseDoor)
{
	struct __ns6__LockDownReleaseDoor soap_tmp___ns6__LockDownReleaseDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockDownReleaseDoor";
	soap_tmp___ns6__LockDownReleaseDoor.ns6__LockDownReleaseDoor = ns6__LockDownReleaseDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__LockDownReleaseDoor(soap, &soap_tmp___ns6__LockDownReleaseDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__LockDownReleaseDoor(soap, &soap_tmp___ns6__LockDownReleaseDoor, "-ns6:LockDownReleaseDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__LockDownReleaseDoor(soap, &soap_tmp___ns6__LockDownReleaseDoor, "-ns6:LockDownReleaseDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_LockDownReleaseDoor(_ns6__LockDownReleaseDoorResponse &ns6__LockDownReleaseDoorResponse)
{
	ns6__LockDownReleaseDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__LockDownReleaseDoorResponse.soap_get(soap, "ns6:LockDownReleaseDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_LockOpenDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__LockOpenDoor *ns6__LockOpenDoor)
{
	struct __ns6__LockOpenDoor soap_tmp___ns6__LockOpenDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockOpenDoor";
	soap_tmp___ns6__LockOpenDoor.ns6__LockOpenDoor = ns6__LockOpenDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__LockOpenDoor(soap, &soap_tmp___ns6__LockOpenDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__LockOpenDoor(soap, &soap_tmp___ns6__LockOpenDoor, "-ns6:LockOpenDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__LockOpenDoor(soap, &soap_tmp___ns6__LockOpenDoor, "-ns6:LockOpenDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_LockOpenDoor(_ns6__LockOpenDoorResponse &ns6__LockOpenDoorResponse)
{
	ns6__LockOpenDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__LockOpenDoorResponse.soap_get(soap, "ns6:LockOpenDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_LockOpenReleaseDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__LockOpenReleaseDoor *ns6__LockOpenReleaseDoor)
{
	struct __ns6__LockOpenReleaseDoor soap_tmp___ns6__LockOpenReleaseDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/LockOpenReleaseDoor";
	soap_tmp___ns6__LockOpenReleaseDoor.ns6__LockOpenReleaseDoor = ns6__LockOpenReleaseDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__LockOpenReleaseDoor(soap, &soap_tmp___ns6__LockOpenReleaseDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__LockOpenReleaseDoor(soap, &soap_tmp___ns6__LockOpenReleaseDoor, "-ns6:LockOpenReleaseDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__LockOpenReleaseDoor(soap, &soap_tmp___ns6__LockOpenReleaseDoor, "-ns6:LockOpenReleaseDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_LockOpenReleaseDoor(_ns6__LockOpenReleaseDoorResponse &ns6__LockOpenReleaseDoorResponse)
{
	ns6__LockOpenReleaseDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__LockOpenReleaseDoorResponse.soap_get(soap, "ns6:LockOpenReleaseDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int DoorControlBindingProxy::send_DoubleLockDoor(const char *soap_endpoint_url, const char *soap_action, _ns6__DoubleLockDoor *ns6__DoubleLockDoor)
{
	struct __ns6__DoubleLockDoor soap_tmp___ns6__DoubleLockDoor;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/doorcontrol/wsdl/DoubleLockDoor";
	soap_tmp___ns6__DoubleLockDoor.ns6__DoubleLockDoor = ns6__DoubleLockDoor;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns6__DoubleLockDoor(soap, &soap_tmp___ns6__DoubleLockDoor);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns6__DoubleLockDoor(soap, &soap_tmp___ns6__DoubleLockDoor, "-ns6:DoubleLockDoor", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns6__DoubleLockDoor(soap, &soap_tmp___ns6__DoubleLockDoor, "-ns6:DoubleLockDoor", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int DoorControlBindingProxy::recv_DoubleLockDoor(_ns6__DoubleLockDoorResponse &ns6__DoubleLockDoorResponse)
{
	ns6__DoubleLockDoorResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns6__DoubleLockDoorResponse.soap_get(soap, "ns6:DoubleLockDoorResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
