// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbproducer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProducerClient is the client API for Producer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerClient interface {
	GetStreamInfo(ctx context.Context, in *GetStreamInfoReq, opts ...grpc.CallOption) (*GetStreamInfoRsp, error)
	GetStreamData(ctx context.Context, in *GetStreamDataReq, opts ...grpc.CallOption) (Producer_GetStreamDataClient, error)
}

type producerClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerClient(cc grpc.ClientConnInterface) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) GetStreamInfo(ctx context.Context, in *GetStreamInfoReq, opts ...grpc.CallOption) (*GetStreamInfoRsp, error) {
	out := new(GetStreamInfoRsp)
	err := c.cc.Invoke(ctx, "/pbproducer.Producer/GetStreamInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) GetStreamData(ctx context.Context, in *GetStreamDataReq, opts ...grpc.CallOption) (Producer_GetStreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Producer_ServiceDesc.Streams[0], "/pbproducer.Producer/GetStreamData", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerGetStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Producer_GetStreamDataClient interface {
	Recv() (*GetStreamDataRsp, error)
	grpc.ClientStream
}

type producerGetStreamDataClient struct {
	grpc.ClientStream
}

func (x *producerGetStreamDataClient) Recv() (*GetStreamDataRsp, error) {
	m := new(GetStreamDataRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProducerServer is the server API for Producer service.
// All implementations must embed UnimplementedProducerServer
// for forward compatibility
type ProducerServer interface {
	GetStreamInfo(context.Context, *GetStreamInfoReq) (*GetStreamInfoRsp, error)
	GetStreamData(*GetStreamDataReq, Producer_GetStreamDataServer) error
	mustEmbedUnimplementedProducerServer()
}

// UnimplementedProducerServer must be embedded to have forward compatible implementations.
type UnimplementedProducerServer struct {
}

func (UnimplementedProducerServer) GetStreamInfo(context.Context, *GetStreamInfoReq) (*GetStreamInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamInfo not implemented")
}
func (UnimplementedProducerServer) GetStreamData(*GetStreamDataReq, Producer_GetStreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStreamData not implemented")
}
func (UnimplementedProducerServer) mustEmbedUnimplementedProducerServer() {}

// UnsafeProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerServer will
// result in compilation errors.
type UnsafeProducerServer interface {
	mustEmbedUnimplementedProducerServer()
}

func RegisterProducerServer(s grpc.ServiceRegistrar, srv ProducerServer) {
	s.RegisterService(&Producer_ServiceDesc, srv)
}

func _Producer_GetStreamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).GetStreamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbproducer.Producer/GetStreamInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).GetStreamInfo(ctx, req.(*GetStreamInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_GetStreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStreamDataReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProducerServer).GetStreamData(m, &producerGetStreamDataServer{stream})
}

type Producer_GetStreamDataServer interface {
	Send(*GetStreamDataRsp) error
	grpc.ServerStream
}

type producerGetStreamDataServer struct {
	grpc.ServerStream
}

func (x *producerGetStreamDataServer) Send(m *GetStreamDataRsp) error {
	return x.ServerStream.SendMsg(m)
}

// Producer_ServiceDesc is the grpc.ServiceDesc for Producer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Producer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbproducer.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStreamInfo",
			Handler:    _Producer_GetStreamInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStreamData",
			Handler:       _Producer_GetStreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "producer.proto",
}
